// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	Parent *string `json:"parent"`
}

type NewCategory struct {
	Name   string  `json:"name"`
	Parent *string `json:"parent"`
}

type NewProduct struct {
	Name        string  `json:"name"`
	Price       string  `json:"price"`
	Description *string `json:"description"`
	Stock       *string `json:"stock"`
	CategoryID  string  `json:"categoryId"`
}

type NewSale struct {
	Quantity    int     `json:"quantity"`
	TotalAmount float64 `json:"total_amount"`
	ProductID   string  `json:"productId"`
}

type Product struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Price       string    `json:"price"`
	Description *string   `json:"description"`
	Sku         *string   `json:"sku"`
	Stock       *string   `json:"stock"`
	Category    *Category `json:"category"`
}

type Sale struct {
	ID          string   `json:"id"`
	Quantity    int      `json:"quantity"`
	TotalAmount float64  `json:"total_amount"`
	Product     *Product `json:"product"`
}
